### ISSUE TITLE
REGRESSION: dotnet-runtime-70's release of 16th of May is causing "version `GLIBC_2.34' not found"

### ISSUE THREAD

**Issue by siwatanejo** [canonical/dotnet-snap#14]
Hello,

Is this the repository that hosts the sources for this snap? https://snapcraft.io/dotnet-runtime-70

I had a CI job creating a snap that has dotnet-runtime-70 as a dependency, and today my CI job started to fail (not when generating the snap package, but when testing it), without having changed anything in our end.

When I try to run my app from the command line I get:

```
/usr/bin/env: /snap/dotnet-fsharp-helloworld/x1/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/bin/env)
Error: Process completed with exit code 1.
```

This was not happening 2 days ago so I think it has something to do with the update that happened on the 16 of May.

If you want to see the log of the CI run: https://github.com/packwallet/packwallet/actions/runs/9123678246/job/25086590176

Log of the CI run that worked, 2 days ago: https://github.com/packwallet/packwallet/actions/runs/9066760393/job/24910390088

**Comment by mateusrodrigues** [comment]
@siwatanejo also, heads up that you may be impacted by this, since you also use the `dotnet` plugin: https://github.com/canonical/snapcraft/issues/4825

**Comment by mateusrodrigues** [comment]
Looking at the GitHub Actions results from commit [`12d6216`](https://github.com/webwarrior-ws/packwallet/commit/12d621624ba76bd6e11cbd9685031b647ecf6a59) and with no further problems being reported, it looks like this issue has been fixed with the upload to latest/candidate (revision 31).

Therefore I'm promoting revision 31 of dotnet-runtime-70 from latest/candidate to latest/stable and closing this issue as resolved. A similar fix has also been uploaded to the dotnet-runtime-60 and dotnet-runtime-80 snaps.

Feel free to reopen the issue if needed.
